title:            Waqar Aqeel
description:      Welcome to my site.
url:              //waqaraqeel.github.io
# url:              //localhost:4000
#disqus_shortname: jponttuset

# Owner/author information
owner:
  name:           Waqar Aqeel
  avatar:         me.jpg
  bio:            I'm from Orangi Town, Pakistan. Currently in Cambridge, MA. Interested in networking, systems, reading, and mountains.
  email:          waqeel _at_ cs _dot_ duke _dot_ edu
  # facebook:       waqarahmedaqeel
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # twitter: jponttuset
  linkedin: waqaraqeel
  # google_scholar: VCBBx24AAAAJ
  #  google_plus: 113718226018314522413
  github: waqaraqeel
# Analytics and webmaster tools stuff goes here
#google_analytics: UA-52736040-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Publications
    url: /publications
  - title: Teaching
    url: /teaching
  - title: CV
    url: /assets/cv.pdf

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
